#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

export SOURCE_FILES="typesystem tests"

${PREFIX}autoflake --in-place --recursive $SOURCE_FILES
${PREFIX}isort --project=typesystem $SOURCE_FILES
${PREFIX}black $SOURCE_FILES
