#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv --cov=typesystem --cov=tests --cov-fail-under=100 --cov-report=term-missing ${@}
${PREFIX}mypy typesystem --ignore-missing-imports --disallow-untyped-defs
${PREFIX}autoflake --recursive typesystem tests
${PREFIX}black typesystem tests --check
